build:
  command: yarn workspace site build
  functions: site/functions
  publish: site/public

redirects:
  - from: https://learnwithjason.netlify.com/*
    to: https://www.learnwithjason.dev/:splat
    status: 301
    force: true

plugins:
  - type: netlify-plugin-gatsby-cache
    config:
      gatsby_public_dir: site/public
      gatsby_cache_dir: site/.cache
